id: I0EC9FE5B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T21:07:20+00:00'
last_modified: '2022-06-10T05:07:33.506072+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13759
  title: གསུང་འབུམ། གྲགས་པ་བཤད་སྒྲུབ། ༼གློག་ཀླད་པར་མ།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    0E01:
      image_group_id: I1KG15427
      title: Volume 1 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 480
      order: 1
      base_file: 0E01.txt
    A832:
      image_group_id: I1KG15428
      title: Volume 2 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 416
      order: 2
      base_file: A832.txt
    A0F0:
      image_group_id: I1KG15429
      title: Volume 3 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 352
      order: 3
      base_file: A0F0.txt
    4C40:
      image_group_id: I1KG15430
      title: Volume 4 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 452
      order: 4
      base_file: 4C40.txt
    A4A4:
      image_group_id: I1KG15431
      title: Volume 5 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 464
      order: 5
      base_file: A4A4.txt
    FDDD:
      image_group_id: I1KG15432
      title: Volume 6 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 380
      order: 6
      base_file: FDDD.txt
    43B6:
      image_group_id: I1KG15433
      title: Volume 7 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 439
      order: 7
      base_file: 43B6.txt
    C8C9:
      image_group_id: I1KG15434
      title: Volume 8 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 460
      order: 8
      base_file: C8C9.txt
    0E4B:
      image_group_id: I1KG15435
      title: Volume 9 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 444
      order: 9
      base_file: 0E4B.txt
    09BB:
      image_group_id: I1KG15436
      title: Volume 10 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 524
      order: 10
      base_file: 09BB.txt
    AA0B:
      image_group_id: I1KG15437
      title: Volume 11 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 380
      order: 11
      base_file: AA0B.txt
    A064:
      image_group_id: I1KG15438
      title: Volume 12 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 374
      order: 12
      base_file: A064.txt
    8F22:
      image_group_id: I1KG15439
      title: Volume 13 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 432
      order: 13
      base_file: 8F22.txt
    739A:
      image_group_id: I1KG15440
      title: Volume 14 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      total_pages: 432
      order: 14
      base_file: 739A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
