id: P000395
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG13759
  title: གསུང་འབུམ། གྲགས་པ་བཤད་སྒྲུབ། ༼གློག་ཀླད་པར་མ།༽
  author: ''
  volumes:
    f4598856e4e74eeb8492b54bfe1393e1:
      image_group_id: I1KG15427
      title: Volume 1 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      volume_number: 1
      total_pages: 480
    c923836399694bf78b62f76dd56f20c9:
      image_group_id: I1KG15428
      title: Volume 2 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      volume_number: 2
      total_pages: 416
      base_file: v002.txt
    aadf5c7dc51a4ff49bc28d6574518ab7:
      image_group_id: I1KG15429
      title: Volume 3 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      volume_number: 3
      total_pages: 352
      base_file: v003.txt
    430b3a50ccfa42e7a1ce59e1cd7f1359:
      image_group_id: I1KG15430
      title: Volume 4 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      volume_number: 4
      total_pages: 452
      base_file: v004.txt
    547b362446be401897e0cc32b380688d:
      image_group_id: I1KG15431
      title: Volume 5 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      volume_number: 5
      total_pages: 464
      base_file: v005.txt
    cbb2453d0bcc4d579e4b1f531e5c6256:
      image_group_id: I1KG15432
      title: Volume 6 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      volume_number: 6
      total_pages: 380
      base_file: v006.txt
    a3bf1d50c52d4c30a9318be7de953051:
      image_group_id: I1KG15433
      title: Volume 7 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      volume_number: 7
      total_pages: 439
      base_file: v007.txt
    34a27f1ec0174c63938db5a1fe658a3e:
      image_group_id: I1KG15434
      title: Volume 8 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      volume_number: 8
      total_pages: 460
      base_file: v008.txt
    f96652c2148e43e5a852f8e6f07d57f2:
      image_group_id: I1KG15435
      title: Volume 9 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      volume_number: 9
      total_pages: 444
      base_file: v009.txt
    6139a94fa12849268581a5c93b1337a7:
      image_group_id: I1KG15436
      title: Volume 10 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      volume_number: 10
      total_pages: 524
      base_file: v010.txt
    f5eb895e40e84f7d9d1c1801598bfdf4:
      image_group_id: I1KG15437
      title: Volume 11 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      volume_number: 11
      total_pages: 380
      base_file: v011.txt
    ff36f77156f54d80b3edfdb707d66e1b:
      image_group_id: I1KG15438
      title: Volume 12 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      volume_number: 12
      total_pages: 374
      base_file: v012.txt
    350a575849254850b59377efd9ca969b:
      image_group_id: I1KG15439
      title: Volume 13 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      volume_number: 13
      total_pages: 432
      base_file: v013.txt
    0418ab19915f44d2bd33c61076646771:
      image_group_id: I1KG15440
      title: Volume 14 of gsung 'bum/_grags pa bshad sgrub/ (glog klad par ma/)
      volume_number: 14
      total_pages: 432
      base_file: v014.txt
